### ISSUE TITLE
Enhancement: Add parameters

### ISSUE THREAD

**Issue by b-morgan** [Booli/OctoPrint-ActionTriggerPlugin#1]
I have external 12v fans attached to the Pi via a PiHat. I want the speed of those fans to mirror the speed set by the G-code commands M106 S<n> (<n> = 0-255) and M107 (= M106 S0).

If I post-process the G-code output and change, for example, M106 S100 to M106 S100\n// action: fan S100 I'd like the S100 (and anything else) to be appended to the system command listed.

**Comment by jneilliii** [comment]
@b-morgan are you confusing this plugin with [Action Commands](https://plugins.octoprint.org/plugins/actioncommands/)? This plugin only seems to be able to control opening doors and filament runout, and as new maintainer I want to clear out any old issues.

**Comment by b-morgan** [comment]
Of course I'm confused, I'm 71 years old. :-)

I'm afraid I don't recall my thought processes from almost 3 years ago. What I can tell you is that I solved my problem by writing my own plugin, [Fan Speed Mirror](https://github.com/b-morgan/OctoPrint-FanSpeedMirror). This issue can be closed.
