### ISSUE TITLE
Add Python 3 compatibility

### ISSUE THREAD

**Issue by Poikilos** [Booli/OctoPrint-ActionTriggerPlugin#2]
OctoPrint now supports Python 3 compatibility. Recently they added a plugin called "Python 3 Check" which suggests to the user to add an issue at the plugin's repo for adding Python 3 compatibilty.

**Comment by Booli** [comment]
Hey @poikilos ! 

Thanks for the message. Unfortunately I am not active any more in the development of this plugin. I would highly encourage anyone to Python3-ify this plugin, it should not be too hard. Any PR I can easily pull if tested.

**Comment by cp2004** [comment]
Hey @Booli 
I went ahead and added the Python 3 compatibility stuff, and a software update hook so users will be able to update, should you choose to change it. While it is not strictly required, highly recommended. Let me know if there's anything you want changed

**Comment by Booli** [comment]
That is awesome, thank you so much (on behalf of all users of this plugin :)). I will pull merge it and make a release.

**Comment by Booli** [comment]
Merged and new release made. 
Thanks all
