### ISSUE TITLE
[Bug] Fails to detect upgrade already done

### ISSUE THREAD

**Issue by KenLucke** [Booli/OctoPrint-ActionTriggerPlugin#4]
After upgrading everything to Python 3, I get a notification from ATP that an update for Python 3 is available.  Telling it to update causes an update to appear to happen, then a reboot, and the same notice appears again (and again... and again...)

This happens on all printers and all instances of OctoPrint.

![CR-10 v2 (Yellow) LAN  OctoPrint  2020-09-10 13-01-42](https://user-images.githubusercontent.com/57936294/92796291-ec4df580-f365-11ea-8f08-c941f1256e45.jpg)

**Comment by Bacon-Fixation** [comment]
I also have this issue but I have fix 

I changed `plugin_version = "0.1"` to `plugin_version = "1.1"` in the setup.py to match the Version check to stop this bug.
I hope this helps ya

**Comment by Booli** [comment]
This should be fixed by the latest commit.

**Comment by jneilliii** [comment]
Hey guys, could you please test our recent changes to the plugin by copying/pasting the URL below into plugin manager > get more > ...from URL and clicking install. Just want to make sure this plugin is still functioning properly after some of the tweaks I have made after taking over maintenance of the plugin.

```
https://github.com/Booli/OctoPrint-ActionTriggerPlugin/archive/refs/tags/1.1.1rc1.zip
```
