### ISSUE TITLE
[Abandoned / Up for adoption] Not able to maintain this plugin any longer

### ISSUE THREAD

**Issue by Booli** [Booli/OctoPrint-ActionTriggerPlugin#6]
Hey Community, 

I am not able to maintain this plugin, so I will make one last release and then it's up for adoption / abandoned by me. 

This plugin has around ~300 active users and should be very easy to maintain or to upgrade even! A perfect place for a plugin-development-starter :)

**Comment by jneilliii** [comment]
I have adopted the plugin.
